### ISSUE TITLE
Institution Screen

### ISSUE THREAD

**Issue by alizul01** [4RSIM3R/raise-hope#5]
**Institution Type** : 

1. Non-profit organization
2. Community group
3. School or educational institution
4. Government agency
5. Religious organization
6. Health or medical institution
7. Arts and cultural organization
8. Environmental organization
9. Animal welfare organization
10. Social enterprise or business with a social mission

![image](https://user-images.githubusercontent.com/62384197/222963651-0891f44d-a16b-4d44-ac85-d1392fc7378f.png)

**Comment by tioirawan** [comment]
Will do
